# Generated by Django 6.0 on 2026-03-13 16:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dtrsdx9x9/image/upload/v1773418355/default_htbobq.jpg', max_length=255),
        ),
    ]
