# Generated by Django 6.0 on 2026-01-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_bio_userbook_is_favourite_userfollow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbook',
            name='is_favourite',
        ),
    ]
