# Generated by Django 6.0 on 2026-02-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userbook_is_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='pages_read',
            field=models.IntegerField(default=0),
        ),
    ]
