# Generated by Django 6.0 on 2026-02-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userbook_pages_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='status',
            field=models.CharField(choices=[('reading', 'Reading'), ('completed', 'Completed'), ('wishlist', 'Wishlist')], max_length=20),
        ),
    ]
